### PR TITLE
chore/ci: add job-level if to condition on version change commits

### PR DESCRIPTION
**Pull request by mrcnski**
Note: This PR may change based on further replies to [this thread](https://github.community/t5/GitHub-Actions/Use-a-job-level-conditional-if-to-check-command-output/m-p/42911/highlight/false#M5170).

### CODE REVIEW

**Comment by lionel-faber** [comment]
Introducing this change will make "Rebase and merge" compulsory since the latest commit (i.e. the commit that the action is being run against) might be a merge commit.
cc: @nbaksalyar

**Comment by mrcnski** [comment]
Can you elaborate @lionel1704 ? This change should reduce LoC without making any functional changes.

**Comment by lionel-faber** [comment]
If a PR is merged then the latest commit will be something like:
`Merge pull request #153 from joshuef/VersionBump0.7.2`
This would break the version change logic, yes?

**Comment by mrcnski** [comment]
I think so, but we can check other commits as well. We can use an or-conditional to check if either the last or second-to-last commit is a version change. If you're happy with that I would be willing to make the change here, it should be fairly simple.

**Pull request closed without merging**
